= NFJS Python Flask Lambda
:toc:

== Getting Started

Make sure you have `Python` and `pipenv` installed. Then run these commands:

[source,bash]
----
$ pipenv install --dev
$ pipenv shell # <1>
$ code .
----
<1> if you are new to Python and `pipenv` you will want to setup your shell to automatically enter the virtual `pipenv shell` whenever you cd into this directory. You can also do this manually but if you are like me you'll forget more than you'll remember.

== Setup VSCode for debugging

Put  the following into a file named `launch.json` located in your `.vscode` directory:

[source]
----
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "serverless_python_example/app.py",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "0"
            },
            "args": ["run", "--no-debugger", "--no-reload"],
            "jinja": true
        }
    ]
}
----

== Useful `curl` commands

[source,bash]
----
$ curl -X POST -H "Content-Type: application/json" \
      -d '{"name": "Chris Lahdesmaki", "cloud": "Azure", "pl": "C++", "pl2": "PL1"}' \
      -Lik http://127.0.0.1:5000/employees && echo
$
$ curl -Lik http://127.0.0.1:5000/employees/<uuid> # <1>
$
$ curl -Lik http://127.0.0.1:5000/employees/b884f9b5-b7c9-4c3b-a87b-97f4cfdb3702 # <2>
----
<1> Use the UUID returned from the `curl -X POST` command above.

<2> There's a default entry in the DyamoDB table with this UUID

== Useful SAM and AWS cli Commands

[source,bash]
----
$ sam local generate-event apigateway aws-proxy --path employees --method GET > event.json # <1>
$
$ awslocal lambda invoke --function-name \
  arn:aws:lambda:us-east-1:000000000000:function:ExampleLambda \
  --payload file://event.json output.json && cat output.json # <2>
----
<1> Run https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html[SAM] to generage an API Gateway based, event you can use to invoke your Lambda.

<2> Use the event generated above and invoke the Lambda directly, simulating a REST API call via an API Gateway.

